import { BookData } from '@/types/types'

export const Books: BookData[] = [
  {
    title: '채식주의자',
    author: '한강',
    progress: 70,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 50,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 30,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 90,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 20,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 60,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 80,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 40,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 25,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    progress: 55,
    description: '폭력적인 육식 사회에서 내면의 평화를 찾아가는 여성의 이야기',
    cover: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg',
    publisher: '',
    pubDate: '',
  },
]
